functional:
  - "Поиск: по ключевым словам, категориям, частичному совпадению (palette → Eyeshadow Palette)"
  - "Чёткая иерархия категорий (Косметика → Тени → Палетки)"
  - "Фильтрация по: цене (с валидацией), бренду (мультиселект), рейтингу (1-5 звёзд)"
  - "Мобильная версия: адаптивная вёрстка, touch-навигация"
  - "Карточка товара: фото (3+ ракурса), описание, отзывы, рейтинг"
  - "Корзина: добавление/удаление, пересчёт суммы, валидация пустой корзины"

non-functional:
  - "Кросс-браузерность: Chrome, Firefox, Safari, Edge, Yandex (последние 2 версии)"
  - "Мобильные ОС: адаптация под iOS/Android (тесты через BrowserStack)"
  - "Локализация: русский/английский, переключение без перезагрузки"
  - "Производительность: главная <1.5 сек, каталог <2 сек"
  - "Безопасность: HTTPS обязателен, маскировка персональных данных"
