functional:
  search:
    - Поиск товаров по ключевому слову
    - Поддержка частичного совпадения (например, "palette" → "Eyeshadow Palette")
    - Поиск по категориям
    - Четкая иерархия категорий (например "Косметика → Тени → Палетки")
  filtering:
    - Фильтрация товаров по:
      - Ценовому диапазону (с валидацией ввода)
      - Бренду (мультиселект)
      - Рейтингу (от 1 до 5 звезд)
  mobile:
    - Полнофункциональная мобильная версия:
      - Адаптивная верстка
      - Удобная навигация на touch-устройствах
  product:
    - Детальная карточка товара должна содержать:
      - Фото (минимум 3 ракурса)
      - Описание с техническими характеристиками
      - Отзывы и рейтинг
  cart:
    - Добавление/удаление товаров
    - Пересчет итоговой суммы в реальном времени
    - Валидация при пустой корзине

non-functional:
  compatibility:
    - Кросс-браузерная поддержка (Yandex, Chrome, Firefox, Safari, Edge последних 2 версий)
    - Адаптация под iOS/Android (проверка через BrowserStack)
  localization:
    - Полная локализация интерфейса (русский/английский)
    - Переключение языка без перезагрузки страницы
  performance:
    - Время загрузки страницы:
      - Главная: < 1.5 сек
      - Каталог: < 2 сек
  security:
    - Защита данных:
      - HTTPS обязателен
      - Маскировка персональных данных в логах
